[tool.poetry]
name = "ml-lambda"
version = "0.1.0"
description = ""
authors = ["Richardbmk"]
readme = "README.md"
packages = [{include = "ml_lambda"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
